import { Navbar } from "components/website/navbar/Navbar";
import { Carousel } from "components/website/carousel/Carousel";
import type { NextPage } from "next";
import Head from "next/head";
import { Discover } from "components/website/discover/Discover";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Carousel />
        <Discover />
      </main>
    </div>
  );
};

export default Home;
